language: python
python:
  - 2.7

install:
  - pip install pytest pytest-cov python-coveralls
  - pip install -r requirements.txt
  - git clone https://github.com/microserv/entangled-dht entangled && cd entangled
  - python setup.py install
  - cd ..

script:
  - py.test src --cov=src

after_success:
  coveralls

sudo: false
